fragment_f001: {

  text: 
   "Учёный проводит эксперимент, фиксирует данные и сравнивает результат с гипотезой. Если результат не совпадает — он ищет объяснение. Это называется научный метод.",

  idea_summary: [
    "научный метод - это процесс выдвижения гипотез и их проверок"
  ],

  key_thoughts: [
    "выдвигается гипотеза",
    "проводится эксперимент",
    "по факту эксперимента фиксируются данные",
    "результат сравнивается в гипотезой",
    "если гипотеза расходится с результатом ищется объяснение"
  ],


  thought_flows: {
   "формулировка гипотезы -> дизайн эксперимента для проверки",
   "эксперимент порождает -> данные",
   "из данных -> формулируется результат",
   "результат сравнивается с -> гипотезой",
   "гипотеза расходится с -> результатом -> поиск причин",
  }
}