meta: {

  name: "Структурное описание научного метода",
  type: "исследовательская инженерия мышления",

  initiator_state: {
    role: "исследователь",
    stage: "частично ориентирован, но без полной структуры",
    goal: "понять и выразить научный метод как понятную, живую и масштабируемую систему"
  },

  audience: {
    profile: "думающая часть широкой аудитории",
    барьер: "неформализованность, элитарность, избыточная абстрактность",
    потребность: "применимое и когнитивно ясное понимание, а не только набор лозунгов"
  },

  implicit_assumptions: {
    architecture_not_rulebook: "Научный метод — это не просто набор правил, а когнитивная архитектура",
    includes_heuristics_and_limits: "Он включает эвристики, ошибки, границы применимости",
    decomposable_as_structure: "Его можно (и нужно) разложить на структурные узлы, как ты делаешь в YAML",
    lacks_unified_map: "Сейчас в культуре нет полной, визуально и логически собранной карты научного метода, хотя он разрозненно описан в разных источниках"
  }
}

